name: Default SDK
on: 
  push:
    branches: 
      - '**'
    tags-ignore:
      - '*.*'
  workflow_dispatch:

jobs:
  test:
    name: Setup and test
    runs-on: ubuntu-latest
    steps:
      - uses: globalid/github-actions/npm-setup@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run lint
      - run: npm run build
